<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="DashBoard.aspx.cs" Inherits="DashBoard" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
<script type='text/javascript' src='https://public.tableau.com/javascripts/api/viz_v1.js'></script><div class='tableauPlaceholder' style='width: 424px; height: 629px;'><noscript><a href='#'><img alt='TopNTeambyPPP_PPS ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;To&#47;TopNTeambyPPP_PPS&#47;TopNTeambyPPP_PPS&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' width='424' height='629' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='site_root' value='' /><param name='name' value='TopNTeambyPPP_PPS&#47;TopNTeambyPPP_PPS' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;To&#47;TopNTeambyPPP_PPS&#47;TopNTeambyPPP_PPS&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='showVizHome' value='no' /><param name='showTabs' value='y' /></object></div>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<script type='text/javascript' src='https://public.tableau.com/javascripts/api/viz_v1.js'></script><div class='tableauPlaceholder' style='width: 500px; height: 629px;'><noscript><a href='#'><img alt='TopNPlayerbyPPPDash ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;To&#47;TopNPlayerbyPPP&#47;TopNPlayerbyPPPDash&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' width='500' height='629' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='site_root' value='' /><param name='name' value='TopNPlayerbyPPP&#47;TopNPlayerbyPPPDash' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;To&#47;TopNPlayerbyPPP&#47;TopNPlayerbyPPPDash&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='showVizHome' value='no' /><param name='showTabs' value='y' /></object></div>
</asp:Content>

